# Generated by Django 4.1.8 on 2023-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antopic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('_id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
