# Generated by Django 4.1.8 on 2023-04-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antopic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('_id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='antopic.topic')),
            ],
        ),
    ]
