# Generated by Django 4.1.8 on 2023-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antopic', '0005_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
