# Generated by Django 4.1.8 on 2023-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antopic', '0008_topic_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(default='processing', max_length=255),
        ),
    ]
